### ISSUE TITLE
Not working when downloding all albums from a singer

### ISSUE THREAD

**Issue by askfriends** [TheKVT/music-dl#1]
Im trying to download all albums from a singer, so when i give it singer url like https://www.qobuz.com/se-en/composer/atif-aslam/595592 it gave error:
```
`AssertionError
  at /usr/local/lib/python3.10/dist-packages/rip/core.py:201 in handle_item
      197│         if media_type not in MEDIA_TYPES:
      198│             if "playlist" in media_type:  # for SoundCloud
      199│                 media_type = "playlist"
      200│ 
    → 201│         assert media_type in MEDIA_TYPES, media_type
      202│         item = MEDIA_CLASS[media_type](client=client, id=item_id)
      203│         self.append(item)
      204│ 
      205│     def _get_download_args(self) -> dict:

If this was unexpected, please open a Bug Report at https://github.com/nathom/streamrip/issues/new/choose`
```

**Comment by Dileepoke** [comment]
Yo  @askfriends
None of the qobuz downloader have support to download composer's discographies, only supports for artists discography. So use artist link of that composer(use search  bar to get link)

> Well, you can use this url to download that composer's discography  https://play.qobuz.com/artist/595592

Sometimes real url regex won't for quboz api stuff
Use this types of various regexes like :

**Tracks:** 
`https://play.qobuz.com/track/<id>`

**Albums**: 
`https://www.qobuz.com/<CountryCode>/album/<AlbumName>/<id>`

`https://play.qobuz.com/album/<id>`

**Artists:**
`https://play.qobuz.com/artist/<id>`

`https://www.qobuz.com/<CountryCode>/interpreter/<ArtistName>/<id> `

**Labels:**
`https://www.qobuz.com/<CountryCode>/label/<LabelName>/download-streaming-albums/<id> `

`https://play.qobuz.com/label/<id> `

**Playlists:** 
`https://play.qobuz.com/playlist/<id>`


Use `https://play.qobuz.com/...../....` if real urls won't work

**Comment by TheKVT** [comment]
Yo  @askfriends
None of the qobuz downloader have support to download composer's discographies, only supports for artists discography. So use artist link of that composer(use search  bar to get link)

> Well, you can use this url to download that composer's discography  https://play.qobuz.com/artist/595592

Sometimes real url regex won't for quboz api stuff
Use this types of various regexes like :

**Tracks:** 
`https://play.qobuz.com/track/<id>`

**Albums**: 
`https://www.qobuz.com/<CountryCode>/album/<AlbumName>/<id>`

`https://play.qobuz.com/album/<id>`

**Artists:**
`https://play.qobuz.com/artist/<id>`

`https://www.qobuz.com/<CountryCode>/interpreter/<ArtistName>/<id> `

**Labels:**
`https://www.qobuz.com/<CountryCode>/label/<LabelName>/download-streaming-albums/<id> `

`https://play.qobuz.com/label/<id> `

**Playlists:** 
`https://play.qobuz.com/playlist/<id>`


Use `https://play.qobuz.com/...../....` if real urls won't work

**Comment by TheKVT** [comment]
Yo  @askfriends
None of the qobuz downloader have support to download composer's discographies, only supports for artists discography. So use artist link of that composer(use search  bar to get link)

> Well, you can use this url to download that composer's discography  https://play.qobuz.com/artist/595592

Sometimes real url regex won't for quboz api stuff
Use this types of various regexes like :

**Tracks:** 
`https://play.qobuz.com/track/<id>`

**Albums**: 
`https://www.qobuz.com/<CountryCode>/album/<AlbumName>/<id>`

`https://play.qobuz.com/album/<id>`

**Artists:**
`https://play.qobuz.com/artist/<id>`

`https://www.qobuz.com/<CountryCode>/interpreter/<ArtistName>/<id> `

**Labels:**
`https://www.qobuz.com/<CountryCode>/label/<LabelName>/download-streaming-albums/<id> `

`https://play.qobuz.com/label/<id> `

**Playlists:** 
`https://play.qobuz.com/playlist/<id>`


Use `https://play.qobuz.com/...../....` if real urls won't work

**Comment by askfriends** [comment]
> Yo @askfriends None of the qobuz downloader have support to download composer's discographies, only supports for artists discography. So use artist link of that composer(use search bar to get link)
> 
> > Well, you can use this url to download that composer's discography  https://play.qobuz.com/artist/595592
> 
> Sometimes real url regex won't for quboz api stuff Use this types of various regexes like :
> 
> **Tracks:** `https://play.qobuz.com/track/<id>`
> 
> **Albums**: `https://www.qobuz.com/<CountryCode>/album/<AlbumName>/<id>`
> 
> `https://play.qobuz.com/album/<id>`
> 
> **Artists:** `https://play.qobuz.com/artist/<id>`
> 
> `https://www.qobuz.com/<CountryCode>/interpreter/<ArtistName>/<id> `
> 
> **Labels:** `https://www.qobuz.com/<CountryCode>/label/<LabelName>/download-streaming-albums/<id> `
> 
> `https://play.qobuz.com/label/<id> `
> 
> **Playlists:** `https://play.qobuz.com/playlist/<id>`
> 
> Use `https://play.qobuz.com/...../....` if real urls won't work

got it thank you!
BTW can you make a telegram bot to download from qobuz and upload to gdrive?

**Comment by askfriends** [comment]
Another querry, can i download directly to my gdrive?
Im asking this if any singer has more than 70gb data, we cant download in colab, so if we can directly download to our gdrive it will be handy.
