### ISSUE TITLE
skips albums, can you fix it?

### ISSUE THREAD

**Issue by askfriends** [TheKVT/music-dl#3]
Im trying to download all albums by an artist whose link is given below, i tried few times but it only downloads 10 12 albums, while there are 67 albums, is it a bug or what?
Link: https://www.qobuz.com/us-en/interpreter/mika-singh/290860

**Comment by Dileepoke** [comment]
#2

**Comment by TheKVT** [comment]
May be problem with your Qobuz account region or it's may not available for streaming, if you think it's really an issue make it on streamrip repo
